config/routes.rb
Looper::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  resources :shares
  resources :tags
  resources :contents
  resources :share_views, :only => [ :create ]

  resources :groups do
    member do
      get 'shares'
    end
  end

  resources :users do
    collection do
      get 'current'
      get 'friends'
    end
  end

  authenticated :user do
  end

  root :to => "home#index"

  get 'dashboard/index'
  

end

app/models/share.rb
class Share < ActiveRecord::Base
  has_many :tags
  has_many :share_views
  belongs_to :group

  #attr_accessible :url, :thumb, :title, :media_type, :description
  #attr_accessible :preview_html, :share_views, :group_id

  #validates :media_type, :inclusion => { :in => ['article', 'audio', 'video', 'photo'] }

  before_save :scrape_data

  def embedly
    client = Embedly::API.new :key => 'e8d4e74f0400420fa8a38df5d50fe26a',
        :user_agent => 'Mozilla/5.0 (compatible; mytestapp/1.0; paulsilvis@gmail.com)'
    obj = client.oembed :url => url
    json_obj = JSON.pretty_generate(obj[0].marshal_dump)

    if obj[0]
      obj = obj[0]
      self.title = obj.title
      self.description = obj.description
      self.preview_html = obj.html
      self.url = obj.url
      self.thumb = obj.thumbnail_url
      self.media_type = obj.type
    end
  end

  def viewers
    if ! group.nil?
      viewers = []
      users = group.users
      for user in users
        usr = user.attributes
        usr[:viewed] = 0
        for view in share_views
          if user.id == view.user_id
            usr[:viewed] = 1
          end
        end
        viewers << usr
      end
      viewers
    else
      []
    end
  end

  private

  def scrape_data
    embedly()
  end
end

app/models/share_view.rb
class ShareView < ActiveRecord::Base
  belongs_to :user
  belongs_to :share

  #attr_accessible :share_id, :user_id

  def self.by_group(group_id)
    ShareView.where('group_id=#{group_id}')
  end

end

app/controllers/shares_controller.rb
class SharesController < ApplicationController
  
  def index
    @shares = current_user.accessible_shares.order("id desc")

    respond_to do |format|
      format.json { render json: @shares.to_json(:methods => :viewers)  }
    end
  end

  def show
    @share = Share.find(params[:id])

    respond_to do |format|
      format.json { render json: @share }
    end
  end

  def new
    @share = Share.new

    respond_to do |format|
      format.json { render json: @share }
    end
  end

  def edit
    @share = Share.find(params[:id])
  end

  def create
    @share = Share.new(params[:share])

    respond_to do |format|
      if @share.save
        format.json { render json: @share, status: :created, location: @share }
      else
        format.json { render json: @share.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @share = Share.find(params[:id])

    respond_to do |format|
      if @share.update_attributes(params[:share])
        format.json { head :no_content }
      else
        format.json { render json: @share.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @share = Share.find(params[:id])
    @share.destroy

    respond_to do |format|
      format.json { head :no_content }
    end
  end
  
  private
  def share_params
    params.require(:share).permit(:url, :thumb, :title, :media_type, :description, :preview_html, :share_views, :group_id)
  end
end

app/helpers/shares_helper.rb
module SharesHelper
end

app/views/shares/_form.html.erb
<%= form_for(@share) do |f| %>
  <% if @share.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@share.errors.count, "error") %> prohibited this share from being saved:</h2>

      <ul>
      <% @share.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shares/edit.html.erb
<h1>Editing share</h1>

<%= render 'form' %>

<%= link_to 'Show', @share %> |
<%= link_to 'Back', shares_path %>

app/views/shares/index.html.erb
<h1>Listing shares</h1>

<table>
  <tr>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @shares.each do |share| %>
  <tr>
    <td><%= share.url %></td>
    <td><%= link_to 'Show', share %></td>
    <td><%= link_to 'Edit', edit_share_path(share) %></td>
    <td><%= link_to 'Destroy', share, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Share', new_share_path %>

app/views/shares/new.html.erb
<h1>New share</h1>

<%= render 'form' %>

<%= link_to 'Back', shares_path %>

app/views/shares/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @share.url %>
</p>


<%= link_to 'Edit', edit_share_path(@share) %> |
<%= link_to 'Back', shares_path %>